# Generated by Django 2.1.2 on 2018-11-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=32)),
                ('item_price', models.CharField(max_length=8)),
                ('item_description', models.CharField(max_length=64)),
                ('contact_number', models.IntegerField(max_length=32)),
                ('item_image', models.CharField(max_length=1000)),
            ],
        ),
    ]
