# Generated by Django 2.1.2 on 2018-11-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='contact_number',
            field=models.CharField(max_length=32),
        ),
    ]
