# Generated by Django 2.1.2 on 2018-11-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protrade', '0004_auto_20181113_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeitems',
            name='exchange_item_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.FileField(upload_to=''),
        ),
    ]
