# Generated by Django 2.1.2 on 2018-11-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protrade', '0005_auto_20181113_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
