# Generated by Django 2.1.2 on 2018-11-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protrade', '0006_auto_20181120_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
