# Generated by Django 2.1.5 on 2019-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protrade', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_name_malaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_image_malaria', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='malaria_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_given_malaria', models.ImageField(max_length=64, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='predicted_label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=8)),
            ],
        ),
    ]
